import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	manifest: '/manifest.json',
	description: 'Generated by create next app',
}

export const viewport: Viewport = {
	themeColor: '#FFFFFF',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
			<Script src='https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js'></Script>
		</html>
	)
}

